service: cart-service
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  stage: dev
  profile: default
  environment:
    NODE_ENV: dev
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
